### ISSUE TITLE
Unsupported reference format when using inline action

### ISSUE THREAD

**Issue by marccampbell** [proactionhq/proaction#76]
The following workflow YAML fails with "unsupported reference":

```
name: ""
on:
  - pull_request

jobs:
  test:
    steps:
    - name: "test"
    - uses: ./actions/containers

```
